package GUIView;

import Controller.GameCont;
import java.awt.Color;
import static java.awt.Color.white;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.IOException;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PLUCSCE
 */
public class GameBoard extends javax.swing.JFrame {

    /**
     * Creates new form GameBoard
     */
    public GameBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        chatTA = new javax.swing.JTextArea();
        msgTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        
        //testview = new javax.swing.JPanel();
        //testview.setBackground(new java.awt.Color(255,255,255));
        
        boardView = new BoardView();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        start = new javax.swing.JMenuItem();
        logOut = new javax.swing.JMenuItem();
        quit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        board30 = new javax.swing.JMenuItem();
        board40 = new javax.swing.JMenuItem();
        board50 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        //setTitle("Play Game");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        chatTA.setBackground(new java.awt.Color(51, 51, 51));
        chatTA.setColumns(20);
        chatTA.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        chatTA.setForeground(new java.awt.Color(255, 255, 255));
        chatTA.setRows(5);
        chatTA.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Window Chat", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monospaced", 0, 14), new java.awt.Color(255, 0, 51))); // NOI18N
        jScrollPane2.setViewportView(chatTA);

        msgTF.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        msgTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msgTFActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel2.setText("                   Player Information");

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel3.setText("       Turn : player ...");

        jLabel4.setText("Player 1");

        jLabel5.setText("Player2");

        //boardView.addMouseListener(new java.awt.event.MouseAdapter() {
        boardView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boardViewMouseClicked(evt);
            }
        });
        
       
        
        
        javax.swing.GroupLayout boardViewLayout = new javax.swing.GroupLayout(boardView);
        boardView.setLayout(boardViewLayout);
        boardViewLayout.setHorizontalGroup(
            boardViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        boardViewLayout.setVerticalGroup(
            boardViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        menu.setText("Menu");
        
        start.setText("Start Game");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        menu.add(start);

        logOut.setText("Log Out");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });
        menu.add(logOut);

        quit.setText("Quit");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });
        menu.add(quit);

        jMenuBar1.add(menu);

        jMenu2.setText("Game Options");

        board30.setText("30x30 (Default)");
        board30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                board30ActionPerformed(evt);
            }
        });
        jMenu2.add(board30);

        board40.setText("40x40");
        board40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                board40ActionPerformed(evt);
            }
        });
        jMenu2.add(board40);

        board50.setText("50x50");
        board50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                board50ActionPerformed(evt);
            }
        });
        jMenu2.add(board50);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);
        
        

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boardView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(msgTF)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(313, 313, 313))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
                        .addGap(192, 192, 192))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(msgTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 231, Short.MAX_VALUE))
                    .addComponent(boardView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }
    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        controller.listen("quit");
    }//GEN-LAST:event_quitActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        controller.listen("logOut");
    }//GEN-LAST:event_logOutActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        controller.listen("close");
    }//GEN-LAST:event_formWindowClosing

    private void board30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_board30ActionPerformed
        controller.updateUserInfo("30");
        controller.listen("size");
        //drawGrid(30,30);
        //testview.setVisible(true);
        /*
    	if(running == false){
    		option = true;
    		n = 30; w = h = 720;
    		load();
    	}
    	else
    		javax.swing.JOptionPane.showMessageDialog(this,"Game is running.");
        */
        //load();
    }//GEN-LAST:event_board30ActionPerformed

    private void board40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_board40ActionPerformed
        //controller.updateUserInfo("40");
        //controller.listen("size");
        //drawGrid(40,40);
        /*
    	if(running == false){
    		option = true;
    		n = 40; w = h = 760;
    		load();
    	}else
    		javax.swing.JOptionPane.showMessageDialog(this,"Game is running.");
        */
    }//GEN-LAST:event_board40ActionPerformed

    private void board50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_board50ActionPerformed
//        controller.updateUserInfo("50");
       // controller.listen("size");
        //drawGrid(50,50);
        /*
    	if(running == false){
    		option = true;
    		n = 50; w = h = 750;
    		load();
    	}else
    		javax.swing.JOptionPane.showMessageDialog(this,"Game is running.");
        */
    }//GEN-LAST:event_board50ActionPerformed

    private void msgTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msgTFActionPerformed
        controller.updateUserInfo("chat_"+msgTF.getText());
        controller.listen("chat");
        msgTF.setText("");
    }//GEN-LAST:event_msgTFActionPerformed
    
    private void boardViewMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        int x, y ;
        x = evt.getX();
        y = evt.getY();
        controller.updateUserInfo(x+"_"+y);
        controller.listen("oneClick");
    }      
    
    private void startActionPerformed(java.awt.event.ActionEvent evt) { 
        controller.listen("start");
        /*
        	if( option == false)
        		System.out.println("choose game.");
        	else
        		running = true;
        */
    }  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameBoard().setVisible(true);
                
                
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private boolean running = false, option = false;
    private javax.swing.JMenuItem board30;
    private javax.swing.JMenuItem board40;
    private javax.swing.JMenuItem board50;
    private javax.swing.JTextArea chatTA;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem logOut;
    private javax.swing.JPanel testview;
    private javax.swing.JMenu menu;
    private javax.swing.JTextField msgTF;
    private javax.swing.JMenuItem quit;
    private javax.swing.JMenuItem start;
    private GameCont controller;
    private BoardView boardView;
    //private Board board;
    //private int n = 30; //Size for the board.
    private int w = 720;
    private int h = 720;
    public int counter ; 
    private BufferedImage img;
    // End of variables declaration//GEN-END:variables


    /**
     * Set the controller to the login view
     * @param controller
     */
    public void setController(GameCont controller){
    	this.controller = controller;
        boardView.setController(controller);
    }  
    
    public void setViewTitle(String title){
        setTitle(title);
    }
    
    
    public void load() {
        //DEBUG
        System.out.println("load is ready");
        testview.setPreferredSize(new Dimension(w, h));
        //img = new BufferedImage(w, h, BufferedImage.TYPE_INT_ARGB);
        Graphics g = img.getGraphics();
        g.setColor(Color.white);
        g.fillRect(0, 0, w, h);
        //reDrawBoard();
       // drawGrid();
    }
    
    public void drawGrid(int rows, int cols){
        
        
        
        System.out.println("this is just the draw grid method being called from the grid select");
        testview.setPreferredSize(new Dimension(w, h));
        img = new BufferedImage(w, h, BufferedImage.TYPE_INT_ARGB);
       Graphics g = testview.getGraphics();
       
        g.setColor(Color.white);
        g.fillRect(0, 0, w, h);
       
       //testview.paintComponents(g);
       System.out.println("gets past paintcomponent");
        //int cols = 30; //change into another variable
        //int rows = 30;//change into another variable
        int BUFFER = 4;
        double cellW = (double) w / cols;//change into another variable
        double cellH = (double) h / rows;//change into another variable
        int cellWi = (int) Math.round(cellW);
        int cellHi = (int) Math.round(cellH);

        int x, y;
        //g.setColor(Color.white);
        //g.fillRect(0, 0, w, h);
        g.setColor(Color.black);
        
        for (int r = 0; r <= rows; r++) {
            y = (int) (r * cellH);
            g.drawLine(0, y, w, y);
        }
        for (int c = 0; c <= cols; c++) {
            x = (int) (c * cellW);
            g.drawLine(x, 0, x, h);
        }
        
        g.dispose();
        //repaint();
    }
    
    public void drawToken(int player, int r, int c){
        Graphics g = img.getGraphics();
        int cols = 30;
        int rows = 30;
        int BUFFER = 4;
        double cellW = (double) WIDTH / cols;
        double cellH = (double) HEIGHT / rows;
        int cellWi = (int) Math.round(cellW);
        int cellHi = (int) Math.round(cellH);

        int x = (int) (c * cellW), y = (int) (r * cellH);
        if (player == 1) {    //Preresent for play are 1
                    g.setColor(Color.blue);
                    g.fillOval(x + BUFFER, y + BUFFER, cellWi - 2 * BUFFER, cellHi - 2 * BUFFER);
                }
                if (player == -1) {   //Preresent for play are 2
                    g.setColor(Color.red);
                    g.fillOval(x + BUFFER, y + BUFFER, cellWi - 2 * BUFFER, cellHi - 2 * BUFFER);
                }
                g.setColor(Color.black);
    }
    
    public void reDrawGrid() {
        /*
        Graphics g = img.getGraphics();
        controller.draw(g, WIDTH, HEIGHT);
        testview.repaint();
                */
        boardView.reDrawBoard();
    }  
    
}
